env:
  global:
    - CC_TEST_REPORTER_ID=b8b69504a2f048f1028d0ee0cf7c08f0e3e7d8b9dbf1d5f012a6ecbd514efb5d
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
script: npm run test
after_success:
  - npm run coverage
notifications:
  email: false
